##
# Created by Thomas Li
# Originally generated 25 November 2022
# Last modified 30 November 2022
#
# This model tracks the list of created feedback forms. Each form involves
# a collection of feedback questions that the instructor may task students
# or other instructors with completing in order to evaluate a presentation.
#
# Forms are represented independently of presentation assignments, so that
# the same form can be reused for multiple assignments in the course
#
# Aside of the autogenerated ID and timestamps, the following fields are
# present:
#
#   (If we get to it, we'll add a column to associate feedback forms with
#   courses)
#
#   title - string (required)
#       A name for the form. Must be unique within each course.
#
class FeedbackForm < ApplicationRecord
  # Create accessors for associated entities
  has_many :questions, class_name: 'FeedbackQuestion', foreign_key: 'form_id'
  has_many :assigned_copies, class_name: 'FeedbackAssignment', foreign_key: 'form_id', dependent: :destroy
  has_many :attached_presentations, through: :assigned_copies, source: :presentation
  has_many :responses, through: :assigned_copies, source: :form

  # Validate presence of required fields
  validates :title, presence: true
end
