##
# Created by Thomas Li
# Originally generated 25 November 2022
# Last modified 30 November 2022
#
# This model defines entries for questions associated with feedback forms.
#
# Aside of the autogenerated ID and timestamps, the following fields are
# present:
#
#   form_id : integer (required)
#     Foreign key into the FeedbackForms table, indicating which form
#     question is part of
#
#     The feedback form ID is a non-unique index
#
#   type_id : integer (required)
#     Foreign key into the FeedbackQuestionType table, indicating which
#     value types the responses can take on
#
#   order : int
#     Indicates the sequence in which questions appear for users
#     for filling out the form - leave nil for arbitrary ordering
#
#   question_text : string (required)
#     Prompt given for users responding to the question
#
#     The feedback form ID and the question text form a unique index
#
class FeedbackQuestion < ApplicationRecord
  # Set associations for foreign keys
  belongs_to :form, class_name: 'FeedbackForm'
  belongs_to :type, class_name: 'FeedbackQuestionType'

  # Add accessors for associated entities
  has_many :settings, class_name: 'FeedbackQuestionSetting', foreign_key: 'question_id'
  has_many :responses, class_name: 'FeedbackResponse', foreign_key: 'question_id'

  # Validate presence of required
  validates :form_id, :type_id, :question_text, presence: true
end
