##
# Created by Thomas Li
# Originally generated 25 November 2022
# Last modified 30 November 2022
#
# This model defines entries for responses to questions in assigned
# feedback forms.
#
# Aside of the autogenerated ID and timestamps, the following fields
# are present:
#
#   assigned_copy_id : integer (required)
#     Foreign key into the FeedbackAssignments table, to indicate which
#     assigned copy of the feedback form is being responded to. The
#     corresponding entry will contain information about which form
#     contains the question, which presenter or presentation group is
#     being evaluated, and which user is doing the evaluation
#
#   question_id : integer (required)
#     Foreign key into the FeedbackQuestions table, indicating which
#     question is being responded to
#
#     The feedback assignment ID and question ID together form a unique
#     index, with each individually being a non-unique index
#
#   value : string
#     Given response value, can be nil for no response
#
class FeedbackResponse < ApplicationRecord
  # Set associations for foreign keys
  belongs_to :assigned_copy, class_name: 'FeedbackAssignment'
  belongs_to :question, class_name: 'FeedbackQuestion'

  # Validate presence of required fields
  validates :assigned_copy_id, :question_id, presence: true
end
