##
# Created by Thomas Li
# Originally generated 25 November 2022
# Last modified 25 November 2022
#
# This model tracks the available question types for feedback forms. Aside
# of the autogenerated ID and timestamps, the following fields are present:
#
#  internal_name : string (required)
#     A verbal identifier for internal use, all-uppercase by convention.
#     Forms a unique index.
#
#  descriptor : string (required)
#     A reader-friendly name for external use
#
#  quantitative : boolean (supposed to be required, but false gets
#  interpreted as nil and vise versa)
#     Set to true to allow the response values (stored as strings by
#     default) to be cast as integers for analytics (e.g. reporting the
#     mean, median, std dev, distribution, etc.))
#
# This is intended to be a reference table, containing a limited set of
# of pre-seeded values that the FeedbackQuestions table draws from,
# as opposed to be being populated by user actions. The following values
# are initialized in the seed script:
#
#   internal_name: "SCALE"
#   descriptor: "Numeric Scale"
#   quantitative: true
#
#   internal_name: "TEXT"
#   descriptor: "Written Response"
#   quantitative: false
#
#   (not currently implemented, possible future addition)
#   internal_name: "QUANT_CHOICE"
#   descriptor: "Quantitative Multiple Choice"
#   quantitative: true
#
class FeedbackQuestionType < ApplicationRecord
  # Validate presence of required fields
  validates :internal_name, presence: true
  validates :descriptor, presence: true

  # Normalize internal name
  before_save { internal_name.upcase! }
end
