##
# Created by Thomas Li
# Originally generated 25 November 2022
# Last modified 30 November 2022
#
# This model defines entries for indicating that a user can view feedback
# given to a given presenter or presentation group on a given feedback form
# for a given presentation assignment
#
# In this version of the program, we're letting this model go unused and
# opting to have all responses be immediately available for expedience
#
# Aside of the autogenerated ID and timestamps, the following fields
# are present:
#
#   form_id : integer (required)
#     Foreign key into FeedbackForms table, indicating which form the
#     responses are being released for
#
#   TO DO: Add columns to indicate the presentation assignment and the
#   evaluated presenter or presentation group
#
#   recipient_id : integer (required)
#     Foreign key into Users table, indicating which user the responses
#     are being released to
#
#     The feedback form ID, presentation assignment ID, presenter/group ID
#     and user ID together form a unique index, with user ID being a non
#     -unique index
#
#   anonymized : boolean
#     Determines whether or not the evaluated user can see the names of
#     the evaluators associated with the responses. Can be overridden by
#     settings on individual questions if set to false, will override
#     settings on individual questions if set to true. Nil gets
#     interpreted as false
#
#   release_date : date
#     Optional specifier for a time at which the responses will become
#     available - set to nil for immediate release
#
class FeedbackRelease < ApplicationRecord
  # Set associations for foreign keys
  belongs_to :form, class_name: 'FeedbackForm'
  belongs_to :recipient, class_name: 'User'

  # Validate presence of required fields
  validates :form_id, :recipient_id, presence: true
end
