##
# Created by Canaan Porter
# Originally generated 27 November 2022
# Last modified 29 November 2022
#
# This model defines presentation entries that can have
# feedback added to and viewed
#
# Aside of the autogenerated ID and timestamps, the following fields
# are present:
#
#   name : String
#     The name of the presentation given
#
#   date : date
#     The date presented on
#
#   users : has and belongs to many
#     The group of students that gave this presentation
#
#   feedback ---- to be implemented
#

class Presentation < ApplicationRecord
  # validations
  validates :name, :date, presence: true

  # associating foreign keys
  has_and_belongs_to_many :users, optional: true
  has_many :assigned_feedbacks, class_name: 'FeedbackAssignment', foreign_key: 'presentation_id'
  has_many :attached_forms, through: :assigned_feedbacks, source: :form
end
